spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:postgres.railway.internal}:${PGPORT:5432}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.springframework.boot.context.config: DEBUG

